<!DOCTYPE html>
<html>

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Cheating AdBlock for 20minutes.fr</title>
	<meta name="description" content="Testing  ">
	<meta name="keywords" content="20minutes, HN Groupe">

	<link href="style.css" rel="stylesheet">

</head>

<body>
	<!-- AddUnit for CaseTest: 20minutes.fr syncronous -->
	<div class="advert rectangle">
		<span>Container pour Add1 - Syncronous</span>
		<script type="text/javascript">
			google_ad_client = "ca-pub-0000000000000000";
			google_ad_slot = "0000000000";
			google_ad_width = 728;
			google_ad_height = 90;
		</script>
		<script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js"></script>

	</div>


	<!-- AddUnit for CaseTest: 20minutes.fr - asyncronous -->
	<div class="advert square">
		<span>Container pour Add2 - Asyncronous</span>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<ins class="adsbygoogle"
		style="display:inline-block;width:336px;height:280px"
		data-ad-client="ca-pub-0000000000000000"
		data-ad-slot="0000000000"></ins>

		<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
		</script>

	</div>

	<script async src="script.js"></script>

</body>

</html>