<!DOCTYPE html>
<html>

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Cheating AdBlock for 20minutes.fr</title>
	<meta name="description" content="Testing  ">
	<meta name="keywords" content="20minutes, HN Groupe">

	<link href="style.css" rel="stylesheet">

</head>

<body>

<h2>20minutes - Alternative pour contrer le phénomène AD Block - Etude de cas 1</h2>

<h3><a href="www.20minutes.fr">www.20minute.fr</a></h3>

	<!-- AddUnit for CaseTest: 20minutes.fr syncronous -->
	<div class="advert rectangle">

		<span class="information">Container pour Add1 - Syncronous</span>

		<p class="empty">Cet container est vide.</p>

		<script type="text/javascript">
			google_ad_client = "ca-pub-0000000000000000";
			google_ad_slot = "0000000000";
			google_ad_width = 728;
			google_ad_height = 90;
		</script>

		<script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js"></script>

	</div>

	<div class="clearfx"></div>

	<!-- AddUnit for CaseTest: 20minutes.fr - asyncronous -->
	<div class="advert square">

		<span class="information">Container pour Add2 - Asyncronous</span>

		<p class="empty">Cet container est vide.</p>

		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<ins class="adsbygoogle"
		style="display:inline-block;width:336px;height:280px"
		data-ad-client="ca-pub-0000000000000000"
		data-ad-slot="0000000000"></ins>

		<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
		</script>

	</div>

	<script async src="script1.js"></script>
	<script src="ajaxLog.js"></script>

</body>

</html>