<?php global $arr ;?>
<body>

	<style>

		<?php echo ".".$arr['css']['advert'] ?> {
			position: relative;
			display: inline-block;
			border: solid 1px blue;
			background: #f3f3f3 ;
			padding: 10px;
			margin: 10px;
			text-align: center;
			font-size: 24px;
			font-style: strong;
			z-index: 100;
		}

		<?php echo ".".$arr['css']['advert'] ?> p {
			position: absolute;
			margin: 5px;
		}

		<?php echo ".".$arr['css']['advert'] ?> p>a {
			font-size: 12px;
		}

		<?php echo ".".$arr['css']['rectangle'] ?> {
			width:728px;
			height:105px;
		}

		<?php echo ".".$arr['css']['square'] ?> {
			width:336px;
			height:295px;
		}

		<?php echo "#".$arr['css']['modal-over'] ?> {
			position: fixed;
			width: 100%;
			height: 100%;
			top: 0;
			left: 0;
			opacity: 80%;
			-webkit-transition: 1ms opacity ease;
			-moz-transition: 1ms opacity ease;
			-ms-transition: 1ms opacity ease;
			-o-transition: 1ms opacity ease;
			transition: 1ms opacity ease;
			background: rgba(0,0,0,.8);
			z-index: 10000;
			text-align: center;
			display: none;
		}

		<?php echo "#".$arr['css']['modal-over'] ?> > div {
			position:absolute;
			top:30%;
			left:30%;
			padding: 50px;
			background-color: rgba(236,225,35,.8);
			border-radius: 10px;
		}

	</style>

	<h2> 20minutes - Alternative pour contrer le phénomène AD Block </h2>
	<h3> Etude de cas
		<?php
		switch ($arr["type"]) {
			case "first":
			echo 1;
			break;
			case "second":
			echo 2;
			break;
			case "third":
			echo 3;
			break;
		}
		?> --- <a href="<?php echo LOG.'log.txt' ?>">Consultez le fichier journal</a> ---
	</h3>

	<h3>Client: <a href="www.20minutes.fr">www.20minute.fr</a></h3>

	<!-- AddUnit for CaseTest: 20minutes.fr syncronous -->
	<div class="<?php echo $arr['css']['advert'] . ' ' . $arr['css']['rectangle']?> ">

		<span class="information">Container pour Add[1] - Syncronous</span>

		<p class="empty">Cet container est vide.</p>

		<script type="text/javascript">
			google_ad_client = "ca-pub-0000000000000000";
			google_ad_slot = "0000000000";
			google_ad_width = 728;
			google_ad_height = 90;
		</script>

		<script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js"></script>

	</div>

	<div class="clearfx"></div>

	<!-- AddUnit for CaseTest: 20minutes.fr - asyncronous -->
	<div class="<?php echo $arr['css']['advert'] . ' ' . $arr['css']['square']?>">

		<span class="information">Container pour Add[2] - Asyncronous</span>

		<p class="empty">Cet container est vide.</p>

		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<ins class="adsbygoogle"
		style="display:inline-block;width:336px;height:280px"
		data-ad-client="ca-pub-0000000000000000"
		data-ad-slot="0000000000"></ins>

		<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
		</script>

	</div>


	<?php script("geolocation", false) ?>
	<?php script("ajaxLog", false) ?>


	<?php if("first" == $arr['type']) : ?>

		<script> a_div =  document.getElementsByClassName("<?php echo $arr['css']['advert'] ?>"); </script>
		<?php script("script_1", false); ?>

	<?php endif	?>


	<?php if("second" == $arr["type"]): ?>

		<div id="<?php echo $arr['css']['modal-over'] ?>">
			<div>
				<h4> Probablement cet navigateur possède l'extension AdBlock activer! <br> Internet est libre parce que des annonces publicitaires. </h4>
				<h2> Laissez-nous d'être le meilleur! </h2>
				<h1> Pour utiliser ce site <br>Désactiver AdBlock maintenant!</h1>
				<a href="https://adblockplus.org/fr/faq_basics#disable" target="_blank">Me montrer comment la faire ca...</a>
			</div>
		</div>

		<script> my_modal = document.getElementById("<?php echo $arr['css']['modal-over'] ?>"); </script>

		<?php script("script_2", false); ?>

	<?php endif ?>

</body>

</html>